openapi: 3.0.1
info:
  title: API EcoLogistics
  version: 1.0.0
  description: API para gestionar envíos (lectura desde CSV → JSON → memoria).
servers:
  - url: /api
paths:
  /ping:
    get:
      summary: Comprobación de estado
      tags: [Utils]
      responses:
        '200':
          description: Servicio en línea
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: ok }
                  service: { type: string, example: EcoLogistics }
                  ts: { type: string, example: "2025-10-29 19:45:00" }

  /envios:
    get:
      summary: Listar todos los envíos
      tags: [Envíos]
      responses:
        '200':
          description: Lista de envíos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Envio'
              examples:
                ejemplo:
                  value:
                    - { id: "001", cliente: "Juan Pérez", direccion: "Quito", estado: "En tránsito" }
                    - { id: "002", cliente: "Marta Lema", direccion: "Cuenca", estado: "Entregado" }

    post:
      summary: Crear un nuevo envío
      tags: [Envíos]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Envio'
            examples:
              ejemplo:
                value: { id: "004", cliente: "Ana Mora", direccion: "Loja", estado: "En tránsito" }
      responses:
        '201':
          description: Envío creado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string, example: creado }

  /envios/{id}:
    get:
      summary: Obtener un envío por ID
      tags: [Envíos]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Envío encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Envio'
        '404':
          description: No encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Envio:
      type: object
      required: [id, cliente, direccion, estado]
      properties:
        id:        { type: string, example: "001" }
        cliente:   { type: string, example: "Juan Pérez" }
        direccion: { type: string, example: "Quito" }
        estado:    { type: string, example: "En tránsito" }

    Error:
      type: object
      properties:
        error: { type: string, example: "Envio no encontrado" }
